language: node_js
node_js:
  - 12
cache: yarn
install:
  - yarn
script:
  - yarn build
after_success:
  - cd build
  - tar czvf ../bundle.tgz *
  - cd ..
before_deploy:
  - export TRAVIS_TAG=`cat VERSION`
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: "bundle.tgz"
  skip_cleanup: true
  on:
    tags: true
    branch: jsonconfig
